name: Custom actions consumer
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Custom action
        id: custom-action
        uses: lfraile-dotnet-2022-workshop/custom-action@v1.2
        with:
          who-to-greet: 'DotNet 2022 Actions Workshop'
      
      - name: Show output
        run: echo '${{ steps.custom-action.outputs.time }}'
