name: Custom actions consumer
on:
  push:
    branches: [ main ]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Custom action
        uses: lfraile-migration-accreditation/custom-action@v1.2
        with:
          who-to-greet: 'Sanofi trainees'
