name: Custom actions consumer
on:
  push:
    branches: [ main, private-actions ]
  workflow_dispatch:
    
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_KEY }}
      
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Custom action
        id: custom-action
        uses: lfraile-dotnet-2022-workshop/custom-action@v1.2
        with:
          who-to-greet: 'DotNet 2022 Actions Workshop'
      
      - name: Show output
        run: echo '${{ steps.custom-action.outputs.time }}'
